language: cpp

install:
  - pip install --user conan cmake

os: linux
compiler: gcc

addons:
  apt:
    packages: lcov

script:
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE .
  - cmake --build . -- -j2
  - ctest -j2
